version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - curl -sSL https://install.python-poetry.org | python3 -
      - $HOME/.local/bin/poetry config virtualenvs.create false
      - $HOME/.local/bin/poetry install
      - pip list
      - echo $VIRTUAL_ENV
      - $HOME/.local/bin/poetry show -t

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
