version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install pdm
      - pdm install -G docs
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
