# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: CI

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "test"
